[build]
builder = "nixpacks"

[deploy]
startCommand = "npx ts-node -r ./tsconfig-paths-bootstrap.js ws-server.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production" 